"""add_organization_logo_url

Revision ID: 1809801ce675
Revises: f839718bc095
Create Date: 2022-12-19 09:15:58.740868

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1809801ce675"
down_revision = "f839718bc095"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("organization", sa.Column("logo_url", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("organization", "logo_url")
    # ### end Alembic commands ###
