"""contact_emails_should_be_nullable

Revision ID: 0ae635406834
Revises: 21a0f4491f8d
Create Date: 2022-11-17 14:31:10.445921

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0ae635406834"
down_revision = "21a0f4491f8d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("dataset", "title", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("dataset", "title", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###
