"""cascade-delete-tags

Revision ID: 45376b50aba5
Revises: 0ae635406834
Create Date: 2022-11-28 13:25:01.010069

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "45376b50aba5"
down_revision = "0ae635406834"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("dataset_tag_tag_id_fkey", "dataset_tag", type_="foreignkey")
    op.create_foreign_key(
        None, "dataset_tag", "tag", ["tag_id"], ["id"], ondelete="cascade"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "dataset_tag", type_="foreignkey")
    op.create_foreign_key(
        "dataset_tag_tag_id_fkey", "dataset_tag", "tag", ["tag_id"], ["id"]
    )
    # ### end Alembic commands ###
