"""change_dataformat_enum_to_string_value

Revision ID: a6fd9d9cdb24
Revises: 1809801ce675
Create Date: 2023-01-03 16:08:09.668663

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "a6fd9d9cdb24"
down_revision = "1809801ce675"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "dataset",
        "publication_restriction",
        existing_type=postgresql.ENUM(
            "LEGAL_RESTRICTION",
            "DRAFT",
            "NO_RESTRICTION",
            name="publication_restriction_enum",
        ),
        nullable=True,
        existing_server_default=sa.text(
            "'NO_RESTRICTION'::publication_restriction_enum"
        ),
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "dataset",
        "publication_restriction",
        existing_type=postgresql.ENUM(
            "LEGAL_RESTRICTION",
            "DRAFT",
            "NO_RESTRICTION",
            name="publication_restriction_enum",
        ),
        nullable=False,
        existing_server_default=sa.text(
            "'NO_RESTRICTION'::publication_restriction_enum"
        ),
    )
    # ### end Alembic commands ###
